// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mttechne.Backend.Junior.Data;

#nullable disable

namespace Mttechne.Backend.Junior.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231202131216_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mttechne.Backend.Junior.Services.Model.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            Nome = "Placa de Vídeo",
                            Valor = 1000
                        },
                        new
                        {
                            ProdutoId = 2,
                            Nome = "Placa de Vídeo",
                            Valor = 1500
                        },
                        new
                        {
                            ProdutoId = 3,
                            Nome = "Placa de Vídeo",
                            Valor = 1350
                        },
                        new
                        {
                            ProdutoId = 4,
                            Nome = "Processador",
                            Valor = 2000
                        },
                        new
                        {
                            ProdutoId = 5,
                            Nome = "Processador",
                            Valor = 2100
                        },
                        new
                        {
                            ProdutoId = 6,
                            Nome = "Memória",
                            Valor = 300
                        },
                        new
                        {
                            ProdutoId = 7,
                            Nome = "Memória",
                            Valor = 350
                        },
                        new
                        {
                            ProdutoId = 8,
                            Nome = "Placa mãe",
                            Valor = 1100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
